services:
  grafana:
    image: grafana/grafana-oss:12.0.2
    ports:
    - 3000:3000

  timescaledb:
    image: timescale/timescaledb:latest-pg17
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgresdb
      PGDATA: data
    ports:
    - 5432:5432
