{
 "title": "Workflow Runs",
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "repository",
    "label": "Repository",
    "query": "SELECT DISTINCT(id) FROM repositories ORDER BY id ASC;"
   },
   {
    "name": "bucket_interval",
    "label": "Bucket Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Orgs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT org_id) FROM repositories"
    }
   ]
  },
  {
   "title": "Unique Workflow Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT workflow_name) FROM workflow_runs\nWHERE time >= $__timeFrom()::timestamptz AND time < $__timeTo()::timestamptz;"
    }
   ]
  },
  {
   "title": "Avg Duration by Repo",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 17, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time_bucket_gapfill('$bucket_interval', time) AS time,\n  r.name AS \"metric\",\n  AVG(EXTRACT(epoch FROM duration)) AS \"value\"\nFROM workflow_runs wr\nJOIN repositories r ON wr.repository_id = r.id\nWHERE repository_id in ($repository)\n  AND time >= $__timeFrom()::timestamptz AND time < $__timeTo()::timestamptz\nGROUP BY r.name, time_bucket_gapfill('$bucket_interval', time)\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Total Repositories",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) FROM repositories;"
    }
   ]
  },
  {
   "title": "Total Workflow Runs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 3, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(workflow_name) FROM workflow_runs\nWHERE time >= $__timeFrom()::timestamptz AND time < $__timeTo()::timestamptz;"
    }
   ]
  },
  {
   "title": "Avg Workflow Run Duration by Repo",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT time_bucket_gapfill('$bucket_interval', time) AS time,\n  (r.org_id, r.name) AS \"metric\",\n  AVG(EXTRACT(epoch FROM duration)) AS \"value\"\nFROM workflow_runs wr\nJOIN repositories r ON wr.repository_id = r.id\nWHERE repository_id in ($repository)\n  AND time >= $__timeFrom()::timestamptz AND time < $__timeTo()::timestamptz\nGROUP BY r.org_id, r.name, time_bucket_gapfill('$bucket_interval', time)\nORDER BY time;"
    }
   ]
  }
 ]
}