{{- if .Values.configMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "timescale-db-helm.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.configMap.data }}
  {{ $key }}: |+
{{ $value | indent 4 }}
{{- end }}
{{- end }}