apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "timescale-db-helm.labels" . | nindent 4 }}
stringData:
{{- range $key, $val := .Values.secrets }}
  {{ $key }}: {{ $val | quote }}
{{- end }}