apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "timescale-db-helm.labels" . | nindent 4 }}
spec:
  {{- if .Values.ports }}
  ports:
  {{- range $i, $port := .Values.ports }}
  - name: {{ $port.name }}
    port: {{ default $port.containerPort $port.servicePort }}
    targetPort: {{ $port.containerPort }}
    protocol: {{ $port.protocol | upper | quote }}
  {{- end }}
  {{- end }}
  selector:
    {{- include "timescale-db-helm.selector-labels" . | nindent 4 }}